In [1]:
import numpy as np
import torch

In [2]:
#creating transpose with numpy

arr=np.array([[1,2,3,4]])

print(arr)
print(arr.T)


[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [4]:
#using np.transpose
print(arr)
print(np.transpose(arr))

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [6]:
#transpose using pytorch

my_tensor=torch.tensor([[1,2,3,4],[5,6,7,8]])
print(my_tensor)
print(my_tensor.T)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
